const { log } = require('console')
const os=require('os')
// console.log(os.EOL)
// console.log(os.arch())
// console.log(os.availableParallelism())
// console.log(os.constants)
// console.log(os.cpus())
// console.log(os.homedir())
// console.log(os.getPriority(0))
// console.log(os.loadavg())
// console.log(os.hostname())
// console.log(os.machine())
// console.log(os.networkInterfaces())
// console.log(os.platform())
console.log(os.tmpdir());
console.log(os.version())
console.log(os.userInfo())
console.log(os.type())
